# coding: utf-8

"""
    SMCCD Directory API

    This is SMCCD Directory API documentation. The API requires basic authentication username and password pair to access the data.  # noqa: E501

    OpenAPI spec version: v1.1
    Contact: apiteam@smccd.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "smccd-directory"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="SMCCD Directory API",
    author_email="apiteam@smccd.edu",
    url="",
    keywords=["Swagger", "SMCCD Directory API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    This is SMCCD Directory API documentation. The API requires basic authentication username and password pair to access the data.  # noqa: E501
    """
)
