# coding: utf-8

"""
    SMCCD Schedule API

    This is SMCCD Schedule API documentation. The API requires basic authentication username and password pair to access the data.  # noqa: E501

    OpenAPI spec version: v1
    Contact: webmaster@smccd.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import smccd_websmart
from smccd_websmart.models.course_department import CourseDepartment  # noqa: E501
from smccd_websmart.rest import ApiException


class TestCourseDepartment(unittest.TestCase):
    """CourseDepartment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCourseDepartment(self):
        """Test CourseDepartment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = smccd_websmart.models.course_department.CourseDepartment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
