# coding: utf-8

"""
    SMCCD Schedule API

    This is SMCCD Schedule API documentation. The API requires basic authentication username and password pair to access the data.  # noqa: E501

    OpenAPI spec version: v1
    Contact: webmaster@smccd.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import smccd_websmart
from smccd_websmart.models.api_error400_response_error import ApiError400ResponseError  # noqa: E501
from smccd_websmart.rest import ApiException


class TestApiError400ResponseError(unittest.TestCase):
    """ApiError400ResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiError400ResponseError(self):
        """Test ApiError400ResponseError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = smccd_websmart.models.api_error400_response_error.ApiError400ResponseError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
