# coding: utf-8

"""
    SMCCD Schedule API

    This is SMCCD Schedule API documentation. The API requires basic authentication username and password pair to access the data.  # noqa: E501

    OpenAPI spec version: v1
    Contact: webmaster@smccd.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import smccd_websmart
from smccd_websmart.api.courses_api import CoursesApi  # noqa: E501
from smccd_websmart.rest import ApiException


class TestCoursesApi(unittest.TestCase):
    """CoursesApi unit test stubs"""

    def setUp(self):
        self.api = CoursesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_courses_by_crn(self):
        """Test case for get_courses_by_crn

        Get course with CRN  # noqa: E501
        """
        pass

    def test_get_courses_by_query(self):
        """Test case for get_courses_by_query

        List courses with optional query parameters  # noqa: E501
        """
        pass

    def test_get_courses_by_term_crn(self):
        """Test case for get_courses_by_term_crn

        Get course with term code and crn  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
