# coding: utf-8

"""
    SMCCD Schedule API

    This is SMCCD Schedule API documentation. The API requires basic authentication username and password pair to access the data.  # noqa: E501

    OpenAPI spec version: v1
    Contact: webmaster@smccd.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SectionDates(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'meet_date': 'str',
        'meet_start_date': 'datetime',
        'meet_end_date': 'datetime'
    }

    attribute_map = {
        'meet_date': 'meet_date',
        'meet_start_date': 'meet_start_date',
        'meet_end_date': 'meet_end_date'
    }

    def __init__(self, meet_date=None, meet_start_date=None, meet_end_date=None):  # noqa: E501
        """SectionDates - a model defined in Swagger"""  # noqa: E501
        self._meet_date = None
        self._meet_start_date = None
        self._meet_end_date = None
        self.discriminator = None
        if meet_date is not None:
            self.meet_date = meet_date
        if meet_start_date is not None:
            self.meet_start_date = meet_start_date
        if meet_end_date is not None:
            self.meet_end_date = meet_end_date

    @property
    def meet_date(self):
        """Gets the meet_date of this SectionDates.  # noqa: E501


        :return: The meet_date of this SectionDates.  # noqa: E501
        :rtype: str
        """
        return self._meet_date

    @meet_date.setter
    def meet_date(self, meet_date):
        """Sets the meet_date of this SectionDates.


        :param meet_date: The meet_date of this SectionDates.  # noqa: E501
        :type: str
        """

        self._meet_date = meet_date

    @property
    def meet_start_date(self):
        """Gets the meet_start_date of this SectionDates.  # noqa: E501


        :return: The meet_start_date of this SectionDates.  # noqa: E501
        :rtype: datetime
        """
        return self._meet_start_date

    @meet_start_date.setter
    def meet_start_date(self, meet_start_date):
        """Sets the meet_start_date of this SectionDates.


        :param meet_start_date: The meet_start_date of this SectionDates.  # noqa: E501
        :type: datetime
        """

        self._meet_start_date = meet_start_date

    @property
    def meet_end_date(self):
        """Gets the meet_end_date of this SectionDates.  # noqa: E501


        :return: The meet_end_date of this SectionDates.  # noqa: E501
        :rtype: datetime
        """
        return self._meet_end_date

    @meet_end_date.setter
    def meet_end_date(self, meet_end_date):
        """Sets the meet_end_date of this SectionDates.


        :param meet_end_date: The meet_end_date of this SectionDates.  # noqa: E501
        :type: datetime
        """

        self._meet_end_date = meet_end_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SectionDates, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SectionDates):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
