# coding: utf-8

"""
    SMCCD Schedule API

    This is SMCCD Schedule API documentation. The API requires basic authentication username and password pair to access the data.  # noqa: E501

    OpenAPI spec version: v1
    Contact: webmaster@smccd.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SectionInstructor(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'first_name': 'str',
        'last_name': 'str',
        'email': 'str',
        'links': 'SectionInstructorLinks'
    }

    attribute_map = {
        'name': 'name',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'email': 'email',
        'links': '_links'
    }

    def __init__(self, name=None, first_name=None, last_name=None, email=None, links=None):  # noqa: E501
        """SectionInstructor - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._first_name = None
        self._last_name = None
        self._email = None
        self._links = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if email is not None:
            self.email = email
        if links is not None:
            self.links = links

    @property
    def name(self):
        """Gets the name of this SectionInstructor.  # noqa: E501


        :return: The name of this SectionInstructor.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SectionInstructor.


        :param name: The name of this SectionInstructor.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def first_name(self):
        """Gets the first_name of this SectionInstructor.  # noqa: E501


        :return: The first_name of this SectionInstructor.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this SectionInstructor.


        :param first_name: The first_name of this SectionInstructor.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this SectionInstructor.  # noqa: E501


        :return: The last_name of this SectionInstructor.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this SectionInstructor.


        :param last_name: The last_name of this SectionInstructor.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this SectionInstructor.  # noqa: E501


        :return: The email of this SectionInstructor.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this SectionInstructor.


        :param email: The email of this SectionInstructor.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def links(self):
        """Gets the links of this SectionInstructor.  # noqa: E501


        :return: The links of this SectionInstructor.  # noqa: E501
        :rtype: SectionInstructorLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this SectionInstructor.


        :param links: The links of this SectionInstructor.  # noqa: E501
        :type: SectionInstructorLinks
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SectionInstructor, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SectionInstructor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
