# coding: utf-8

"""
    SMCCD Schedule API

    This is SMCCD Schedule API documentation. The API requires basic authentication username and password pair to access the data.  # noqa: E501

    OpenAPI spec version: v1
    Contact: webmaster@smccd.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SectionTime(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'meet_time': 'str',
        'meet_begin_time': 'str',
        'meet_end_time': 'str'
    }

    attribute_map = {
        'meet_time': 'meet_time',
        'meet_begin_time': 'meet_begin_time',
        'meet_end_time': 'meet_end_time'
    }

    def __init__(self, meet_time=None, meet_begin_time=None, meet_end_time=None):  # noqa: E501
        """SectionTime - a model defined in Swagger"""  # noqa: E501
        self._meet_time = None
        self._meet_begin_time = None
        self._meet_end_time = None
        self.discriminator = None
        if meet_time is not None:
            self.meet_time = meet_time
        if meet_begin_time is not None:
            self.meet_begin_time = meet_begin_time
        if meet_end_time is not None:
            self.meet_end_time = meet_end_time

    @property
    def meet_time(self):
        """Gets the meet_time of this SectionTime.  # noqa: E501


        :return: The meet_time of this SectionTime.  # noqa: E501
        :rtype: str
        """
        return self._meet_time

    @meet_time.setter
    def meet_time(self, meet_time):
        """Sets the meet_time of this SectionTime.


        :param meet_time: The meet_time of this SectionTime.  # noqa: E501
        :type: str
        """

        self._meet_time = meet_time

    @property
    def meet_begin_time(self):
        """Gets the meet_begin_time of this SectionTime.  # noqa: E501


        :return: The meet_begin_time of this SectionTime.  # noqa: E501
        :rtype: str
        """
        return self._meet_begin_time

    @meet_begin_time.setter
    def meet_begin_time(self, meet_begin_time):
        """Sets the meet_begin_time of this SectionTime.


        :param meet_begin_time: The meet_begin_time of this SectionTime.  # noqa: E501
        :type: str
        """

        self._meet_begin_time = meet_begin_time

    @property
    def meet_end_time(self):
        """Gets the meet_end_time of this SectionTime.  # noqa: E501


        :return: The meet_end_time of this SectionTime.  # noqa: E501
        :rtype: str
        """
        return self._meet_end_time

    @meet_end_time.setter
    def meet_end_time(self, meet_end_time):
        """Sets the meet_end_time of this SectionTime.


        :param meet_end_time: The meet_end_time of this SectionTime.  # noqa: E501
        :type: str
        """

        self._meet_end_time = meet_end_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SectionTime, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SectionTime):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
