# coding: utf-8

"""
    SMCCD Directory API

    This is SMCCD Directory API documentation. The API requires basic authentication username and password pair to access the data.  # noqa: E501

    OpenAPI spec version: v1.1
    Contact: apiteam@smccd.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DirectoryAddress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'room': 'str',
        'street': 'str',
        'city': 'str',
        'state': 'str',
        'postal_code': 'str'
    }

    attribute_map = {
        'room': 'room',
        'street': 'street',
        'city': 'city',
        'state': 'state',
        'postal_code': 'postal_code'
    }

    def __init__(self, room=None, street=None, city=None, state=None, postal_code=None):  # noqa: E501
        """DirectoryAddress - a model defined in Swagger"""  # noqa: E501
        self._room = None
        self._street = None
        self._city = None
        self._state = None
        self._postal_code = None
        self.discriminator = None
        if room is not None:
            self.room = room
        if street is not None:
            self.street = street
        if city is not None:
            self.city = city
        if state is not None:
            self.state = state
        if postal_code is not None:
            self.postal_code = postal_code

    @property
    def room(self):
        """Gets the room of this DirectoryAddress.  # noqa: E501


        :return: The room of this DirectoryAddress.  # noqa: E501
        :rtype: str
        """
        return self._room

    @room.setter
    def room(self, room):
        """Sets the room of this DirectoryAddress.


        :param room: The room of this DirectoryAddress.  # noqa: E501
        :type: str
        """

        self._room = room

    @property
    def street(self):
        """Gets the street of this DirectoryAddress.  # noqa: E501


        :return: The street of this DirectoryAddress.  # noqa: E501
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street):
        """Sets the street of this DirectoryAddress.


        :param street: The street of this DirectoryAddress.  # noqa: E501
        :type: str
        """

        self._street = street

    @property
    def city(self):
        """Gets the city of this DirectoryAddress.  # noqa: E501


        :return: The city of this DirectoryAddress.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this DirectoryAddress.


        :param city: The city of this DirectoryAddress.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def state(self):
        """Gets the state of this DirectoryAddress.  # noqa: E501


        :return: The state of this DirectoryAddress.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this DirectoryAddress.


        :param state: The state of this DirectoryAddress.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def postal_code(self):
        """Gets the postal_code of this DirectoryAddress.  # noqa: E501


        :return: The postal_code of this DirectoryAddress.  # noqa: E501
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code):
        """Sets the postal_code of this DirectoryAddress.


        :param postal_code: The postal_code of this DirectoryAddress.  # noqa: E501
        :type: str
        """

        self._postal_code = postal_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DirectoryAddress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DirectoryAddress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
