# coding: utf-8

"""
    SMCCD Directory API

    This is SMCCD Directory API documentation. The API requires basic authentication username and password pair to access the data.  # noqa: E501

    OpenAPI spec version: v1.1
    Contact: apiteam@smccd.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DirectoryLinks(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_self': 'DirectoryProfileImage',
        'district_directory': 'DirectoryLinksDistrictDirectory'
    }

    attribute_map = {
        '_self': 'self',
        'district_directory': 'district_directory'
    }

    def __init__(self, _self=None, district_directory=None):  # noqa: E501
        """DirectoryLinks - a model defined in Swagger"""  # noqa: E501
        self.__self = None
        self._district_directory = None
        self.discriminator = None
        if _self is not None:
            self._self = _self
        if district_directory is not None:
            self.district_directory = district_directory

    @property
    def _self(self):
        """Gets the _self of this DirectoryLinks.  # noqa: E501


        :return: The _self of this DirectoryLinks.  # noqa: E501
        :rtype: DirectoryProfileImage
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this DirectoryLinks.


        :param _self: The _self of this DirectoryLinks.  # noqa: E501
        :type: DirectoryProfileImage
        """

        self.__self = _self

    @property
    def district_directory(self):
        """Gets the district_directory of this DirectoryLinks.  # noqa: E501


        :return: The district_directory of this DirectoryLinks.  # noqa: E501
        :rtype: DirectoryLinksDistrictDirectory
        """
        return self._district_directory

    @district_directory.setter
    def district_directory(self, district_directory):
        """Sets the district_directory of this DirectoryLinks.


        :param district_directory: The district_directory of this DirectoryLinks.  # noqa: E501
        :type: DirectoryLinksDistrictDirectory
        """

        self._district_directory = district_directory

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DirectoryLinks, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DirectoryLinks):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
