# coding: utf-8

"""
    SMCCD Directory API

    This is SMCCD Directory API documentation. The API requires basic authentication username and password pair to access the data.  # noqa: E501

    OpenAPI spec version: v1.1
    Contact: apiteam@smccd.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import smccd_directory
from smccd_directory.api.location_api import LocationApi  # noqa: E501
from smccd_directory.rest import ApiException


class TestLocationApi(unittest.TestCase):
    """LocationApi unit test stubs"""

    def setUp(self):
        self.api = LocationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_directory_by_location(self):
        """Test case for get_directory_by_location

        List directory by location in url path  # noqa: E501
        """
        pass

    def test_get_directory_by_location_query(self):
        """Test case for get_directory_by_location_query

        List directory by optional location query parameter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
