# coding: utf-8

"""
    SMCCD Directory API

    This is SMCCD Directory API documentation. The API requires basic authentication username and password pair to access the data.  # noqa: E501

    OpenAPI spec version: v1.1
    Contact: apiteam@smccd.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import smccd_directory
from smccd_directory.api.username_api import UsernameApi  # noqa: E501
from smccd_directory.rest import ApiException


class TestUsernameApi(unittest.TestCase):
    """UsernameApi unit test stubs"""

    def setUp(self):
        self.api = UsernameApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_directory_by_username(self):
        """Test case for get_directory_by_username

        Get directory information by username in url path  # noqa: E501
        """
        pass

    def test_get_photo_by_user_email(self):
        """Test case for get_photo_by_user_email

        Get directory information by username in url path  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
