# coding: utf-8

"""
    SMCCD Directory API

    This is SMCCD Directory API documentation. The API requires basic authentication username and password pair to access the data.  # noqa: E501

    OpenAPI spec version: v1.1
    Contact: apiteam@smccd.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import smccd_directory
from smccd_directory.models.api_error404_response import ApiError404Response  # noqa: E501
from smccd_directory.rest import ApiException


class TestApiError404Response(unittest.TestCase):
    """ApiError404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiError404Response(self):
        """Test ApiError404Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = smccd_directory.models.api_error404_response.ApiError404Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
