# coding: utf-8

"""
    SMCCD Directory API

    This is SMCCD Directory API documentation. The API requires basic authentication username and password pair to access the data.  # noqa: E501

    OpenAPI spec version: v1.1
    Contact: apiteam@smccd.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import smccd_directory
from smccd_directory.models.api_response_embedded import ApiResponseEmbedded  # noqa: E501
from smccd_directory.rest import ApiException


class TestApiResponseEmbedded(unittest.TestCase):
    """ApiResponseEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiResponseEmbedded(self):
        """Test ApiResponseEmbedded"""
        # FIXME: construct object with mandatory attributes with example values
        # model = smccd_directory.models.api_response_embedded.ApiResponseEmbedded()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
